source "https://rubygems.org"

gem "pry"
gem "rake"
gem "ruboty-alias"
gem "ruboty-cron"
# gem "ruboty-github"
gem "ruboty-google_image"
gem "ruboty-lgtm"
gem "ruboty-redis"
gem "ruboty-slack"
gem "ruboty-scorekeeper"
gem "ruboty-zoi"
gem "ruboty-sushiyuki"
gem "ruboty-syoboi_calendar"
#gem "ruboty-misawa", git: "https://github.com/mzp/ruboty-misawa.git"
gem "ruboty-japan_weather"
gem "ruboty-delay"
gem "ruboty-echo"
gem "ruboty-nullpo", git: "https://github.com/mallowlabs/ruboty-nullpo.git"
#gem "ruboty-rss"
gem "ruboty-aa"
